services:
  db:
    image: postgres:16-alpine
    container_name: cart-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - cart_data_new:/var/lib/postgresql/data # Renamed to force a fresh start

  api:
    build: .
    container_name: cart-api
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db

volumes:
  cart_data_new:
